@startuml Diagrama_Clases_BrokerMQTT

!theme mars
skinparam linetype ortho
skinparam backgroundColor #FFFFFF
skinparam nodesep 80
skinparam ranksep 100
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml
LAYOUT_LANDSCAPE()

package configurador{
class ConfiguradorApplication {
  + ConfiguradorApplication():
  + start(Stage): void
  + main(String[]): void
}
class ConfiguradorController {
  + ConfiguradorController():
  - onIniciarESP32ButtonClick(): void
  - actualizarCriptomonedasESP32(): void
  - onQuitarActivasButtonClick(): void
  - actualizarEstadoBotones(boolean): void
  - mostrarAlerta(String, String, AlertType): void
  + initialize(URL, ResourceBundle): void
  - inicializarCriptomonedasPorDefecto(): void
  - agregarMensaje(String): void
  - onAgregarActivasButtonClick(): void
  - onDetenerESP32ButtonClick(): void
  - onConectarButtonClick(): void
  - onAgregarButtonClick(): void
}
class Criptomoneda {
  + Criptomoneda(String, String):
  + simboloProperty(): StringProperty
  + toString(): String
  + nombreProperty(): StringProperty
  + valorCriticoProperty(): DoubleProperty
   valorCritico: double
   simbolo: String
   nombre: String
}
class MQTTService {
  + MQTTService(String, String):
  + unsubscribeFromTopic(String): void
  + detenerESP32(): void
  + disconnect(): void
  + iniciarESP32(): void
  + connect(): boolean
  + subscribeToTopic(String): void
  + enviarComando(String): void
  + addMessageListener(Consumer<String>): void
  - notifyListeners(String, String): void
  + actualizarCriptomonedas(List<Criptomoneda>): void
  + removeMessageListener(Consumer<String>): void
   connected: boolean
}
}
ConfiguradorController   -[#595959,dashed]->  Criptomoneda            : "«create»"
ConfiguradorController  "1" *-[#595959,plain]-> "criptomonedas\n*" Criptomoneda
ConfiguradorController   -[#595959,dashed]->  MQTTService             : "«create»"
ConfiguradorController  "1" *-[#595959,plain]-> "mqttService\n1" MQTTService
ConfiguradorApplication  -[#595959,dashed]->  ConfiguradorController  : "«use»"
MQTTService         -[#595959,dashed]->  Criptomoneda          : "«use»"
@enduml

